server:
  port: 30000
  context-path: /
spring:
  datasource:
    url: jdbc:mysql://XXXXXX:3306/master?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: XXXXX
    password: XXXXX
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    hibernate:
      ddl-auto: none
